import React from 'react'
import { Spin } from 'antd';
const Loader = () => {
    return (
        <div>
            <Spin size={large }/>
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
            //letspinloaderforapiwaiting
        </div>
    )
}

export default Loader
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire
//tomorrowisfire